# Generated by Django 4.2 on 2023-05-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk_ticket_update", "0002_zendeskupdatelogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="zendeskupdatelogs",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
