# Generated by Django 4.2 on 2023-05-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk_ticket_update", "0003_zendeskupdatelogs_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
