# Generated by Django 4.2 on 2023-05-12 04:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zendesk_ticket_update", "0004_testmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmodel",
            name="description",
        ),
    ]
